My Project_2/My_Project/My_Project/Models/TinhCam.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace My_Project.Models
{
    public class TinhCam
    {
        public int ID { set; get; }

        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(100, ErrorMessage = "Số ký tự tối thiểu 5", MinimumLength = 5)]
        public string Title { set; get; }

        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(1000, ErrorMessage = "Số ký tự tối thiểu 20", MinimumLength = 20)]
        public string Body { set; get; }

        [Required(ErrorMessage = "Không được để trống")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { set; get; }


        public int UserProfileUserID { set; get; }
        public virtual UserProfile UserProfile { set; get; }
        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

My Project_2/My_Project/My_Project/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My_Project.Models;

namespace My_Project.Controllers
{
    public class CommentController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.SucKhoe).Include(c => c.TinhCam).Include(c => c.GiaDinh).Include(c => c.TamLy).Include(c => c.HocTap).Include(c => c.CongViec).Include(c => c.XaHoi);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.SucKhoeID = new SelectList(db.SucKhoes, "ID", "Title");
            ViewBag.TinhCamID = new SelectList(db.TinhCams, "ID", "Title");
            ViewBag.GiaDinhID = new SelectList(db.GiaDinhs, "ID", "Title");
            ViewBag.TamLyID = new SelectList(db.TamLies, "ID", "Title");
            ViewBag.HocTapID = new SelectList(db.HocTaps, "ID", "Title");
            ViewBag.CongViecID = new SelectList(db.CongViecs, "ID", "Title");
            ViewBag.XaHoiID = new SelectList(db.XaHois, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        public ActionResult Create(Comment comment, int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.SucKhoeID = idpost;
                comment.TinhCamID = idpost;
                comment.GiaDinhID = idpost;
                comment.TamLyID = idpost;
                comment.HocTapID = idpost;
                comment.CongViecID = idpost;
                comment.XaHoiID = idpost;

                comment.DateCreated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("_viewComment", comment);
            }

            ViewBag.SucKhoeID = new SelectList(db.SucKhoes, "ID", "Title", comment.SucKhoeID);
            ViewBag.TinhCamID = new SelectList(db.TinhCams, "ID", "Title", comment.TinhCamID);
            ViewBag.GiaDinhID = new SelectList(db.GiaDinhs, "ID", "Title", comment.GiaDinhID);
            ViewBag.TamLyID = new SelectList(db.TamLies, "ID", "Title", comment.TamLyID);
            ViewBag.HocTapID = new SelectList(db.HocTaps, "ID", "Title", comment.HocTapID);
            ViewBag.CongViecID = new SelectList(db.CongViecs, "ID", "Title", comment.CongViecID);
            ViewBag.XaHoiID = new SelectList(db.XaHois, "ID", "Title", comment.XaHoiID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.SucKhoeID = new SelectList(db.SucKhoes, "ID", "Title", comment.SucKhoeID);
            ViewBag.TinhCamID = new SelectList(db.TinhCams, "ID", "Title", comment.TinhCamID);
            ViewBag.GiaDinhID = new SelectList(db.GiaDinhs, "ID", "Title", comment.GiaDinhID);
            ViewBag.TamLyID = new SelectList(db.TamLies, "ID", "Title", comment.TamLyID);
            ViewBag.HocTapID = new SelectList(db.HocTaps, "ID", "Title", comment.HocTapID);
            ViewBag.CongViecID = new SelectList(db.CongViecs, "ID", "Title", comment.CongViecID);
            ViewBag.XaHoiID = new SelectList(db.XaHois, "ID", "Title", comment.XaHoiID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SucKhoeID = new SelectList(db.SucKhoes, "ID", "Title", comment.SucKhoeID);
            ViewBag.TinhCamID = new SelectList(db.TinhCams, "ID", "Title", comment.TinhCamID);
            ViewBag.GiaDinhID = new SelectList(db.GiaDinhs, "ID", "Title", comment.GiaDinhID);
            ViewBag.TamLyID = new SelectList(db.TamLies, "ID", "Title", comment.TamLyID);
            ViewBag.HocTapID = new SelectList(db.HocTaps, "ID", "Title", comment.HocTapID);
            ViewBag.CongViecID = new SelectList(db.CongViecs, "ID", "Title", comment.CongViecID);
            ViewBag.XaHoiID = new SelectList(db.XaHois, "ID", "Title", comment.XaHoiID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

My Project_2/My_Project/My_Project/Controllers/TinhCamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My_Project.Models;

namespace My_Project.Controllers
{
    [Authorize]
    public class TinhCamController : Controller
    {
        
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /TinhCam/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var tinhcams = db.TinhCams.Include(t => t.UserProfile);
            return View(tinhcams.ToList());
        }

        //
        // GET: /TinhCam/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            TinhCam tinhcam = db.TinhCams.Find(id);
            ViewData["idpost"] = id;
            if (tinhcam == null)
            {
                return HttpNotFound();
            }
            return View(tinhcam);
        }

        //
        // GET: /TinhCam/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /TinhCam/Create

        [HttpPost]
        public ActionResult Create(TinhCam tinhcam, string Content)
        {
            if (ModelState.IsValid)
            {
                tinhcam.DateCreated = DateTime.Now;

                //tao list cac tag
                List<Tag> Tags = new List<Tag>();
                //tach cac tag theo dau ,
                string[] TagContent = Content.Split(',');
                //lap cac tag vua tach
                foreach (string item in TagContent)
                {
                    //tim xem tag content da co hay chua
                    Tag tagExits = null;

                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        //neu co tag roi thi add them post vao
                        tagExits = ListTag.First();
                        tagExits.TinhCams.Add(tinhcam);
                    }
                    else
                    {
                        //neu chua co tag thi tao moi
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.TinhCams = new List<TinhCam>();
                        tagExits.TinhCams.Add(tinhcam);
                    }
                    // add vao lish cac tag
                    Tags.Add(tagExits);
                }
                //gan List cac tag cho post
                tinhcam.Tags = Tags;

                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                tinhcam.UserProfileUserID = userid;

                db.TinhCams.Add(tinhcam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", tinhcam.UserProfileUserID);
            return View(tinhcam);
        }

        //
        // GET: /TinhCam/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TinhCam tinhcam = db.TinhCams.Find(id);
            if (tinhcam == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", tinhcam.UserProfileUserID);
            return View(tinhcam);
        }

        //
        // POST: /TinhCam/Edit/5

        [HttpPost]
        public ActionResult Edit(TinhCam tinhcam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinhcam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", tinhcam.UserProfileUserID);
            return View(tinhcam);
        }

        //
        // GET: /TinhCam/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TinhCam tinhcam = db.TinhCams.Find(id);
            if (tinhcam == null)
            {
                return HttpNotFound();
            }
            return View(tinhcam);
        }

        //
        // POST: /TinhCam/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TinhCam tinhcam = db.TinhCams.Find(id);
            db.TinhCams.Remove(tinhcam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

My Project_2/My_Project/My_Project/Views/TinhCam/Create.cshtml
@model My_Project.Models.TinhCam

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TinhCam</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileUserID, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserID", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserID)
        </div>

        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new My_Project.Models.Tag().Content)
            @Html.ValidationMessageFor(model =>new My_Project.Models.Tag().Content)
        </div>   

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

My Project_2/My_Project/My_Project/Views/TinhCam/Delete.cshtml
@model My_Project.Models.TinhCam

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TinhCam</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

My Project_2/My_Project/My_Project/Views/TinhCam/Details.cshtml
@model My_Project.Models.TinhCam

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>TinhCam</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>

<div class="display-field">
     <h2>Add Comment</h2>
    </div>
@Html.Partial("_addComment",new My_Project.Models.Comment(), ViewData);

<fieldset>
    <legend>Comment</legend>
    <div id="result">
    @foreach (var comment in Model.Comments.OrderByDescending(x=>x.DateCreated).Take(10))
    {
    <div class="display-field">
        <h2>Cach Day:@Html.DisplayFor(x => comment.LastTime) phút</h2>
    </div>
    
    <div class="display-field">
     Ten: @Html.DisplayFor(x => comment.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(x => comment.Body)
    </div>

    }
        </div>
</fieldset>
    <div class="display-field">
     <h2>Tag</h2>
    </div>
<fieldset>
   
    <legend>Tags</legend>
    @foreach (var tag in Model.Tags)  { 
    
    
    <div class="display-field">
        @Html.RouteLink(tag.Content, new { Controller = "Tag", Action = "Details",id=tag.TagID })       
              
    </div>
   
    }
</fieldset>

<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

My Project_2/My_Project/My_Project/Views/TinhCam/Edit.cshtml
@model My_Project.Models.TinhCam

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TinhCam</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileUserID, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserID", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

My Project_2/My_Project/My_Project/Views/TinhCam/Index.cshtml
@model IEnumerable<My_Project.Models.TinhCam>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

My Project_2/My_Project/My_Project/Views/TinhCam/_addComment.cshtml
@model My_Project.Models.Comment

@using (Html.BeginForm("Create", "Comment",FormMethod.Post, new {id = "my-form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>      

        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>      
        @Html.Hidden("idpost",ViewData["idpost"])

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComment.js"></script>